# Generated by Django 3.2.4 on 2021-06-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20210611_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='style',
        ),
    ]
