# Generated by Django 3.2.4 on 2021-06-11 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_remove_post_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='style',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='styles_names', to='Blog.styles'),
        ),
    ]
