# Generated by Django 3.2.4 on 2021-06-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_post_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='actors',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='producer',
            field=models.JSONField(),
        ),
    ]
