# Generated by Django 3.2.4 on 2021-06-22 22:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_auto_20210623_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entire_rating',
            name='entire_stars',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='entire_rating',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entire_post_name', to='Blog.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='actors',
            field=models.ManyToManyField(to='Blog.Actors'),
        ),
        migrations.AlterField(
            model_name='post',
            name='producer',
            field=models.ManyToManyField(to='Blog.Prod'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 22, 40, 49, 92822, tzinfo=utc)),
        ),
    ]
