# Generated by Django 3.2.4 on 2021-06-23 21:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0015_auto_20210623_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='art_link',
        ),
        migrations.AlterField(
            model_name='post',
            name='actors',
            field=models.ManyToManyField(to='Blog.Actors'),
        ),
        migrations.AlterField(
            model_name='post',
            name='producer',
            field=models.ManyToManyField(to='Blog.Prod'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 21, 14, 25, 458894, tzinfo=utc)),
        ),
    ]
