# Generated by Django 3.2.4 on 2021-06-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authServer', '0003_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='author_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
