# Generated by Django 3.2.4 on 2021-06-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authServer', '0004_auto_20210610_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_id',
        ),
    ]
