# Generated by Django 3.2.4 on 2021-06-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authServer', '0006_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Producer',
            new_name='producer',
        ),
        migrations.AddField(
            model_name='post',
            name='art_link',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
