# Generated by Django 3.2.4 on 2021-06-10 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authServer', '0009_auto_20210610_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_post', to='authServer.useraccount'),
        ),
    ]
