# Generated by Django 3.2.4 on 2021-06-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authServer', '0011_auto_20210610_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='cookie_saves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_user_id', models.CharField(max_length=100)),
                ('cookie_user_token', models.CharField(max_length=100)),
            ],
        ),
    ]
