# Generated by Django 3.2.4 on 2021-06-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authServer', '0013_auto_20210613_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='not_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
