# Generated by Django 3.2.4 on 2021-06-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authServer', '0014_not_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
