# Generated by Django 3.2.4 on 2021-06-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authServer', '0016_moderator_not_moderator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='not_Admin',
        ),
        migrations.DeleteModel(
            name='not_Moderator',
        ),
    ]
