# Generated by Django 3.2.4 on 2021-06-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authServer', '0017_auto_20210615_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='is_moder',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
