# Generated by Django 3.2.4 on 2021-06-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authServer', '0018_moderator_is_moder'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_admin',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
