# Generated by Django 3.2.4 on 2021-06-15 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authServer', '0019_admin_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_Role', models.BooleanField()),
                ('Users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles_names', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
