# Generated by Django 3.2.4 on 2021-06-22 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authServer', '0022_rename_cookie_user_cookie_saves_cookie_user_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_Role',
        ),
        migrations.RemoveField(
            model_name='role',
            name='name',
        ),
        migrations.AlterField(
            model_name='role',
            name='Users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Role_Name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='Name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Name_Role', to='authServer.role_list'),
            preserve_default=False,
        ),
    ]
