# Generated by Django 3.2.4 on 2021-06-30 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authServer', '0024_auto_20210623_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recent_res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_token', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_token_recent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
